### ISSUE TITLE
Support class names like width-1/2

### ISSUE THREAD

**Issue by neeravp** [emmetio/abbreviation#10]
With the advent of utility first css frameworks like tachyon and tailwindcss, class names like width-1/2 etc are very common now a days.
**emmetio** doesn't seem to provide a filter for such names.  Hence no support in ***vscode***
 However PHPStorm is already supporting the use of such class names in emmet

    div.width1/2.relative.p-4
expands to

```html
<div class="width-1/2 relative p-4"></div> 
```
in PHPStorm

Support for such class names via **emmetio** is essential so to say in the world of utility first css frameworks.  
Request you to consider supporting class names like `width-1/2` with a `/` character soon to enable easy use of utility first frameworks.  
Thanks

**Comment by ramya-rao-a** [comment]
cc @sergeche

**Comment by sergeche** [comment]
This will interfere with new Emmet syntax where `/` is used to explicitly mark element as self-closing, e.g. `img.foo/` → `<img class="foo" />`. For such cases, you should write `div[class="width-1/2"]`

**Comment by jesseleite** [comment]
What about escaping the slash, like `div.width-1\/2`?  Is there room for some sort of escaping syntax?

**Comment by sergeche** [comment]
Yes, escaping could work. There’s actually already escaping with `\` for some cases, could work for identifiers too

**Comment by sergeche** [comment]
Fixed in https://github.com/emmetio/emmet: parser now supports character escaping with `\`, you can include any character into element name, class or id
`div.width1\/2.relative.p-4`
