### ISSUE TITLE
Attribute names starting with [ is not supported

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/abbreviation#11]
`div[[a]="b"]` expands correctly to `<div [a]="b"></div>` when trying out in https://docs.emmet.io
But an error gets thrown when this abbreviation is being parsed by this module.

@sergeche #7 was my proposed solution.

You mentioned a new approach in 
https://github.com/emmetio/abbreviation/pull/7#discussion_r135458542

Is there any update on your approach?

**Comment by ramya-rao-a** [comment]
@sergeche This is fixed with #7, but no new version with the fix is released.

Can we have a new version and close this issue?

**Comment by sergeche** [comment]
I’ve suggested better solution in https://github.com/emmetio/abbreviation/pull/7/files#r135458542
Did you tried to use it?

**Comment by sergeche** [comment]
Oh, my bad, I’ve already published it as `@emmetio/abbreviation@0.7.0` :)

**Comment by sergeche** [comment]
It’s already available in `@emmetio/expand-abbreviation@0.7.3`

**Comment by ramya-rao-a** [comment]
Thanks! I'll close this issue
